
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  csSidebar: [{ type: 'autogenerated', dirName: '.' }],
};